version: "3.8"

services:
  frontend:
    build: frontend
    environment:
      REACT_APP_API_URL: http://backend:5050
    ports:
      - "5173:5173"
    networks:
      - mern

  backend:
    build: backend
    ports:
      - "5050:5050"
    networks:
      - mern
    volumes:
      - ./mongo_uri.txt:/run/secrets/mongo_uri
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern
    volumes:
      - ./data:/data/db

networks:
  mern:
    driver: bridge

volumes:
  data:
    driver: local
